#!/usr/bin/env ruby
# Singleshot  Copyright (C) 2008-2009  Intalio, Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


require 'rubygems'
require 'rake'
require 'yaml'
require 'rubygems/source_info_cache'


# The plugins we maintain in vendor/plugins.
$plugins = 'git://github.com/assaf/presenter.git'


def check(message)
  message = message[0, Rake.application.dynamic_width - 9]
  puts "## %s ...\n" % message
  yield
  puts
end

def rake(*args)
  ruby "-S rake --silent #{args.map { |arg| arg.inspect }.join(' ')}"
end

def gem_install(name, options)
  dep = Gem::Dependency.new(name, options[:version] || '>= 0')
  if Gem::SourceIndex.from_installed_gems.search(dep).empty?
    check "Installing #{name} ..." do
      args = ['-S', 'gem', 'install', name, '-v', options['version']]
      args << '--source' << 'http://gems.rubyforge.org' # Always.
      args << '--source' << options['source'] if options['source']
      args << '--no-ri' << '--no-rdoc' << '--format-executable'
      ruby *args
    end
  end
end


namespace 'setup' do

  task 'run'=>['dependencies', 'files', 'database'] do
    Rake::Task['setup:have_fun'].invoke
  end

  task 'dependencies' do
    # Install Rails 2.3.1 (RC2).
    gem_install 'rails', 'version'=>'2.3.1', 'source'=>'http://gems.rubyonrails.org'

    # Install all (incl. development and test) Gem dependencies.
    YAML.load_file('.gems').each do |name, options|
      gem_install name, options
    end

    check "Installing/updating plugins" do
      $plugins.each do |url|
        name, path = url.pathmap('%n'), url.pathmap('vendor/plugins/%n')
        if Dir["#{path}/*"].empty?
          sh "braid add -p #{url.inspect}"
          fail "Plugin #{name} not installed! (looked for it in #{path})" if Dir["#{path}/*"].empty?
        else
          sh "braid update #{path}"
        end
      end
    end
  end

  task 'files' do
    check("Creating new secret key in secret.key") { rake 'secret.key' }
  end

  task 'database' do
    check "Creating a new database" do
      db = YAML.load_file("config/database.yml")['development']
      p "I'm going to create the databse #{db['database']} (#{db['adapter']}) using the account #{db['username']}, password #{db['password']}"
      rake "db:create"
    end
    check("Running all migrations against the new database") { rake "db:migrate:reset" }
    check("Populating development database with mock data")  { rake "db:populate" }
    check "Creating a clone test database" do
      db = YAML.load_file("config/database.yml")['development']
      p "I'm going to create the databse #{db['database']} (#{db['adapter']}) using the account #{db['username']}, password #{db['password']}"
      rake "db:test:clone"
    end
  end

  task 'have_fun' do
    puts <<-TEXT

Done!


   (  (
    )  )
 |_______|--|
 |       |  |
 |       |_/
  \\_____/
 

Delicously fresh ascii coffee, on the house.

To start the server:
  ./script/server

Next, open http://localhost:3000 in your browser and login with
  username:  #{ENV['USER']}
  password:  secret

Have fun!

    TEXT
  end
end

Rake::Task['setup:run'].invoke
